### ISSUE TITLE
Running Evaluation with Custom Data

### ISSUE THREAD

**Issue by afennelly-mitre** [HAAClassic/TreeFormer#6]
I wanted to clarify something wrt using TreeFormer for inference on images **not contained** within the datasets used in the paper. 

Based on the structure of the PTFR, I believe that the model will _work best_ when used with images whose width and height are divisible by 32, the least common multiple (LCM) of 4, 8, 16, and 32. Not only will the model _work best_ with these inputs, but I believe that the current architecture code cannot handle input shapes that do not follow this format. 

Would you agree with this observation? And if so, how do you suggest modifying the code base to handle input sizes that do not follow the above pattern? 

This is something I can implement in a new PR to enable broader use of this great research and model!

**Comment by HAAClassic** [comment]
Yes, I think the model will work best when used with images whose width and height are divisible by 32, which is the least common multiple of 4, 8, 16, and 32. This is because the model architecture is designed to process images in a patch-based manner. I suggest reading these papers to get more information about this structure.
* Pyramid Vision Transformer: A Versatile Backbone for Dense Prediction without Convolutions
* Swin Transformer: Hierarchical Vision Transformer using Shifted Windows
